monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: error
            channels: ["!event"]
        console:
            type: console
            channels: ['!event', '!console']
