version: "3.9"

services:
  upgrader-sdk:
    image: spryker-sdk/upgrader-local:latest
    network_mode: "host"
    build:
      context: ./
      dockerfile: infrastructure/dev.Dockerfile
      args:
          SPRYKER_PARENT_IMAGE: spryker/php:8.1
    environment:
        SPRYKER_XDEBUG_HOST_IP: ${SPRYKER_XDEBUG_HOST_IP:-host.docker.internal}
    tty: true
    command: "/bin/bash"
    volumes:
       - ~/.ssh:/root/.ssh
       - ./:/data
       - {path_to_project}:/data/project

