services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

# Codebase
    Codebase\Application\:
        resource: '../../src/Codebase/Application/*'
        exclude:
            - '../../src/Codebase/Application/Dto/*'

    Codebase\Infrastructure\:
        resource: '../../src/Codebase/Infrastructure/*'
        exclude:
            - '../../src/Codebase/Infrastructure/Exception/*'

    Codebase\Infrastructure\Service\CodebaseService: ~
    Codebase\Application\Service\CodebaseServiceInterface: '@Codebase\Infrastructure\Service\CodebaseService'

    Codebase\Infrastructure\Dependency\Parser\CodebaseToParserBridge: ~
    Codebase\Infrastructure\Dependency\Parser\CodebaseToParserInterface: '@Codebase\Infrastructure\Dependency\Parser\CodebaseToParserBridge'

    Codebase\Infrastructure\Dependency\Finder\CodebaseToFinderBridge: ~
    Codebase\Infrastructure\Dependency\Finder\CodebaseToFinderInterface: '@Codebase\Infrastructure\Dependency\Finder\CodebaseToFinderBridge'

    php.parser:
        class: Codebase\Infrastructure\SourceParser\Parser\PhpParser

    transfer_schema.parser:
        class: Codebase\Infrastructure\SourceParser\Parser\TransferSchemaParser

    database_schema.parser:
        class: Codebase\Infrastructure\SourceParser\Parser\DatabaseSchemaParser

    codebase.service:
        class: Codebase\Infrastructure\Service\CodebaseService

    Codebase\Infrastructure\SourceParser\SourceParser:
        class: Codebase\Infrastructure\SourceParser\SourceParser
        arguments:
            - '@Codebase\Infrastructure\SourceFinder\SourceFinder'
            - {
                param1: '@php.parser',
                param2: '@transfer_schema.parser',
                param3: '@database_schema.parser'
            }

    tooling_configuration_validator.project_prefixes:
        class: Codebase\Infrastructure\ToolingConfigurationReader\Validator\ProjectPrefixesValidator

    Codebase\Infrastructure\ToolingConfigurationReader\ToolingConfigurationReader:
        class: Codebase\Infrastructure\ToolingConfigurationReader\ToolingConfigurationReader
        arguments:
            - {
                param1: '@tooling_configuration_validator.project_prefixes'
            }

# Third-party
    PhpParser\ParserFactory: ~
    Symfony\Component\Finder\Finder: ~
    Symfony\Component\Filesystem\Filesystem: ~
    Symfony\Component\DependencyInjection\Container: ~
