services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

#Core
    Core\Domain\:
        resource: '../../../../Core/Domain/*'

    Core\Infrastructure\:
        resource: '../../../../Core/Infrastructure/*'

    composer.lock.reader:
        class: Core\Infrastructure\Services\ComposerLockReader
