services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Upgrader\:
        resource: '../../src/Upgrader/*'

# SDK Task Definitions
    upgrade.task:
        class: Upgrader\Tasks\Upgrade\UpgradeTask
        tags: [ 'sdk.task' ]

# Console commands
    upgrade.console:
        class: Upgrader\Console\UpgraderConsole
        tags: [ "console.command" ]

# Third-party
    Symfony\Component\Yaml\Yaml: ~
