<?php

/**
 * Copyright © 2016-present Spryker Systems GmbH. All rights reserved.
 * Use of this software requires acceptance of the Evaluation License Agreement. See LICENSE file.
 */

namespace TestProject\MethodIsOverridden;

use TestCore\MethodIsOverridden\CoreRepository;

class ProjectRepository extends CoreRepository
{
    /**
     * @return void
     */
    public function queryTestProjectData(): void
    {
    }

    /**
     * @return void
     */
    public function queryEntityData(): void
    {
        parent::queryEntityData(); // TODO: Change the autogenerated stub
    }
}
