<?php

/**
 * Copyright © 2016-present Spryker Systems GmbH. All rights reserved.
 * Use of this software requires acceptance of the Evaluation License Agreement. See LICENSE file.
 */

namespace TestProject\MethodIsOverridden;

use TestCore\MethodIsOverridden\CoreFactory;
use TestCore\MethodIsOverridden\FooPluginInterface;

class ProjectFactory extends CoreFactory
{
    /**
     * @return void
     */
    public function createTestModel(): void
    {
    }

    /**
     * @return void
     */
    public function createCoreModel(): void
    {
        parent::createCoreModel(); // TODO: Change the autogenerated stub
    }

    /**
     * @return \TestCore\MethodIsOverridden\FooPluginInterface
     */
    protected function getCustomerStepHandler(): FooPluginInterface
    {
        return parent::getCustomerStepHandler();
    }
}
