services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

# ReleaseAppClient
    ReleaseApp\:
        resource: '../../../../ReleaseApp/*'
        exclude:
            - '../../../../ReleaseApp/Domain/Entities/*'
            - '../../../../ReleaseApp/Domain/Client/Request/*'
            - '../../../../ReleaseApp/Domain/Client/Response/*'
            - '../../../../ReleaseApp/Infrastructure/Client/Request/*'
            - '../../../../ReleaseApp/Infrastructure/Shared/Dto/*'
