services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

# ReleaseAppClient
    ReleaseAppClient\Application\:
        resource: '../../../../ReleaseAppClient/Application/*'

    ReleaseAppClient\Infrastructure\:
        resource: '../../../../ReleaseAppClient/Infrastructure/*'

    ReleaseAppClient\Domain\:
        resource: '../../../../ReleaseAppClient/Domain/*'
        exclude:
            - '../../../../ReleaseAppClient/Domain/Dto/*'
            - '../../../../ReleaseAppClient/Domain/Http/HttpResponse.php'
            - '../../../../ReleaseAppClient/Domain/Http/UpgradeAnalysis/*'
            - '../../../../ReleaseAppClient/Domain/Http/UpgradeInstructions/*'
